# Generated by Django 2.1.7 on 2019-08-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='site_media')),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedClue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picturehunt.Clue')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picturehunt.Segment')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('current_clue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picturehunt.Clue')),
                ('path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picturehunt.Path')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('logged_in', models.BooleanField()),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picturehunt.Team')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='segment_order',
            field=models.ManyToManyField(blank=True, to='picturehunt.SegmentOrder'),
        ),
        migrations.AddField(
            model_name='completedclue',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picturehunt.Team'),
        ),
        migrations.AddField(
            model_name='clue',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picturehunt.Segment'),
        ),
    ]
