# Generated by Django 2.1.7 on 2019-08-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picturehunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='picturehunt.Segment'),
        ),
    ]
