# Generated by Django 2.1.7 on 2019-08-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picturehunt', '0002_auto_20190817_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='img',
            new_name='temp_img_url',
        ),
        migrations.AddField(
            model_name='clue',
            name='img_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
