# Generated by Django 2.1.7 on 2019-08-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picturehunt', '0003_auto_20190817_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='temp_img_url',
            new_name='temp_img',
        ),
    ]
