# Generated by Django 2.1.7 on 2019-08-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picturehunt', '0004_auto_20190817_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedclue',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedclue',
            name='guess',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedclue',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
