# Generated by Django 2.1.7 on 2019-08-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picturehunt', '0006_clue_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
