# Generated by Django 2.1.7 on 2019-08-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picturehunt', '0007_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedclue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picturehunt.User'),
        ),
    ]
